### ISSUE TITLE
django-rest-swagger is no longer supported for latest version of Django

### ISSUE THREAD

**Issue by Gr8ayu** [nioperas06/awesome-django-rest-framework#16]
django-rest-swagger is no longer supported for latest version of Django. Adding this info will be really helpful and save a lot of time as this is not mentioned in Official documentation of django-rest-swagger

**Comment by morenoh149** [comment]
submitting a pr that removes that should be pretty easy fyi

**Comment by mohmyo** [comment]
Thank you for rasing out this issue.
I was thinking of adding [drf-yasg](https://github.com/axnsan12/drf-yasg), do we have other packages to add? or do you have other suggestions?

**Comment by Gr8ayu** [comment]
I have added a PR for this issue. drf-yasg works totally fine and it is also recommended in their github repo.
